# RuboCop RSpec extension configuration overrides
# https://github.com/rubocop/rubocop-rspec

RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
    - spec/system/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
    - spec/system/**/*
